### PR TITLE
Fix #222: Mongo::Error::OperationFailure: E11000 duplicate key error index.

### LINKED ISSUE #222: Mongo::Error::OperationFailure: E11000 duplicate key error index:
Hello

When I run the command:
`rake db:mongoid:create_indexes`

I get this error
`
Mongo::Error::OperationFailure: E11000 duplicate key error index: usernames_production.usernames.$_slugs_1  dup key: { : undefined } (11000)`

My model:

  `slug :name`
  `index({approve: 1})`

How to create indexes without this error thank you :)

Thx Boris

### PR DESCRIPTION
**Pull request by dblock**
This is a proposed fix for #222. The problem is that we try to create records with a blank indexed field that generates blank slugs, which causes the unique index to break. We remove the default value of `[]` and store a `nil` slug that works with a `sparse: true` index.

I'd love a code review from @johnnyshields or @digitalplaywright please.

### CODE REVIEW

**Comment by Dan-Nolan** [comment]
Could you also add in a check to see if `to_url` resolves to a nil slug? I ran into a problem with this specifically when users were inputting values like `'-'`. The expression`'-'.to_url` resolves to nil as well, which would also cause this problem.

**Comment by dblock** [comment]
Good point @Dan-Nolan, that seems to work, see specs in https://github.com/digitalplaywright/mongoid-slug/pull/225/commits/218d257e580ae8ea55f99890a5adbd2900496309.

**Comment by Dan-Nolan** [comment]
Sweet! Thanks for checking that out!

**Comment by johnnyshields** [comment]
The bigger question is, should we allow `_slugs` to be blank? I think we should (esp for legacy reasons) and then a sparse index on `_slugs` so that `undefined` is ignored.

The logic to generate a fallback slug maybe should be handled by the implementer on a case-by-case. I'm not convinced that model name by default is such an elegant solution.

**Comment by dblock** [comment]
@johnnyshields You think that `sparse: true` on the index would work?

**Comment by johnnyshields** [comment]
@dblock sparse indexes will ignore documents which do not have the `_slugs` field set, hence are good for incorporating legacy documents. However, if the value of `_slugs` is `nil` (i.e. set in db to null) or `[]` then the unique index error can occur. As long as we're not setting `_slugs` in the DB then a sparse index would work.

As of MongoDB 3.2 there's a better option called "partial indexes" (sparse index on steroids) where you can exclude values `nil` and `[]` from the index as well.

**Comment by dblock** [comment]
@johnnyshields I tried this in https://github.com/dblock/mongoid-slug/tree/fix-222-with-nils. The problem is that we default `slugs` to `[]`. If we remove that we can start setting `nils`. I am still working through two spec failures. I *think* it's better, would like your opinion.

**Comment by dblock** [comment]
@johnnyshields I updated this PR. The problem is that we default `slugs` to `[]`. If we remove that we can start setting `nils`. I am still working through two spec failures. I *think* it's better, would like your opinion.

**Comment by johnnyshields** [comment]
@dblock this needs to be tested. my understanding is that sparse indexes consider "nil" (null) as a value if it's explicitly set in the db, so be careful. I've filed an issue with Mongoid that they need a way to distinguish between nil and unset.

**Comment by dblock** [comment]
@johnnyshields: This *is* tested here, note that I am creating an index in `spec_helper`.

**Comment by dblock** [comment]
I hear you @johnnyshields on 3.2.0, but the code in Mongoid doesn't set the value to `nil`, it leaves it out. At least that's what I see.

**Comment by dblock** [comment]
Ok, I am pretty happy with what's in this PR. 

@johnnyshields: do you think I am doing it all wrong or can I merge this?

@Dan-Nolan: the implementation has changed and since we last spoke, check this out.

@BorisBresciani you opened #222, please check this out.

**Comment by johnnyshields** [comment]
@dblock looks fine to me.

**Comment by Dan-Nolan** [comment]
@dblock Looks great to me; very well documented too! Handling fallback slugs in a case-by-case basis makes sense, and in our case, we ended up not allowing values to resolve to empty stringex urls. It was bad data for us anyhow.

**Comment by dblock** [comment]
FYI was released in 5.3.0

**Pull request merged**
