### PR TITLE
non unique indexes for paranoid docs

### PR DESCRIPTION
**Pull request by tomdmaguire**
fixes paranoid issue described in https://github.com/digitalplaywright/mongoid-slug/pull/172 (updated for latest version of code)

### CODE REVIEW

**Comment by leemhenson** [comment]
+1

**Comment by digitalplaywright** [comment]
Thanks! This is very interesting. I am wondering if it would be better to factor out the index creation into a concern so that people that use the old index format can still upgrade to new versions without recreating indexes. Thought or ideas on better solutions?

**Comment by dblock** [comment]
Bunp @tomdmaguire, care to answer @digitalplaywright's question above? Thanks!

**Comment by johnnyshields** [comment]
FYI MongoDB 3.2 will support partial indexes which will make for a better solution here--you can declare unique as long as `delete_at` does not exist.

http://docs.mongodb.org/manual/release-notes/3.1-dev-series/

**Comment by dblock** [comment]
@johnnyshields @tomdmaguire After merging #172 (via #227) I read everything there's to read here and there and I don't understand what the problem is with paranoid documents and the slug index. Can someone explain it to me like a 2 yo and tell me what we should do with this PR? Thanks.

**Comment by johnnyshields** [comment]
* this gem adds a unique DB index on the `_slugs` field. this means if Doc A has `slugs: ["foo"]` and I try to create Doc B with `slugs: ["foo"]`, the DB itself will not allow Doc B to be saved.
* paranoid docs are "plain old docs" from the DB perspective. so if I have a paranoid deleted doc with `slugs: ["foo"], deleted: true`, the DB doesn't care about `deleted: true`. As long as that deleted paranoid doc is lingering in the DB, I can't save a new doc with `slugs: ["foo"]`
* one might think: ok, the solution here is to set `slugs: nil` on the deleted doc. prior to this PR #227 this wasn't possible because the index was not sparse, meaning that two docs with `_slugs: null` would cause the unique index validation to fail. Now that PR #227 is merged, this approach should be possible.

**Comment by dblock** [comment]
Okay this is a very clear explanation! 

So I think this particular PR can be closed, because it's fully addressed in #227 which effectively "fixes" the scenario that was attempted here?

**Comment by johnnyshields** [comment]
Does paranoid doc remove the value for `_slugs`? It needs to if it's not doing so already.

**Comment by dblock** [comment]
Oh yeah, https://github.com/digitalplaywright/mongoid-slug/blob/382b0999212518b222da93e983d31b1a34feac83/lib/mongoid/slug.rb#L108.

Closing ;)

**Pull request closed without merging**
