### PR TITLE
makes sure Moped is available before we take it

### PR DESCRIPTION
**Pull request by pavlo**
got NameError (uninitialized constant Mongoid::Slug::Criteria::Moped) against MongoId5 before this fix

### CODE REVIEW

**Comment by dblock** [comment]
None of the tests are failing here, is this a code path that's not exercised? Moped should be defined under Mongoid3, why wouldn't it be?

**Comment by pavlo** [comment]
Unfortunately I do not know much about how test infrastructure works on this project so can not prove the situation with a failed test. I can learn the thing on a weekend in a week or two... 

Just needed to fix the issue quickly on a project I am involved in and thought this would be helpful for others though.

**Comment by dblock** [comment]
Are you using mongoid-observers? The issue is fully described in #194, fix in https://github.com/digitalplaywright/mongoid-slug/pull/195.

**Comment by dblock** [comment]
I released 5.2.0 with this fix, I am 99% sure this is the problem, please reopen if it's not fixed with that version of mongoid-slug.

**Pull request closed without merging**
