### PR TITLE
Fix: mongoid_slug:set rake task for Mongoid 5. [DON'T MERGE]

### PR DESCRIPTION
**Pull request by dblock**
Need to make sure the mongoid HEAD build passes, right now there're some issues with mongoid/observers, see https://github.com/chamnap/mongoid-observers/pull/2.

### CODE REVIEW

**Comment by Fudoshiki** [comment]
https://travis-ci.org/Sharevari-Inc/mongoid/builds/136339223

**Comment by Fudoshiki** [comment]
Tests against mri 2.3.1, rails 5.0.0.rc1
- [ ] mongoid tests passed
- [ ] mongoid-observers tests passed
- [ ] mongoid_paranoia tests passed
- [ ] mongoid-slug head tests passed

**Comment by Fudoshiki** [comment]
@dblock want we target master branch on Mongoid HEAD?
https://github.com/Sharevari-Inc/mongoid-slug/commit/ab93caaa680c705a97706e3c11f105e9dff4d85f

**Comment by dblock** [comment]
Yes @Fudoshiki, but generally I am not too excited about trying to keep up with mongoid until there's some RC or something. Of course I'd take pull requests if someone is motivated to use the edge version(s).

**Comment by Fudoshiki** [comment]
@dblock Can You accept PR and merger with master

**Comment by Fudoshiki** [comment]
@dblock I will create PR with simmilar tasks https://github.com/simi/mongoid_paranoia/pull/44

**Comment by Fudoshiki** [comment]
@dblock 
I targeted on Mongoid master branch, can we drop Mongoid 4/5 and ruby < 2.2.2 support in master branch?

https://github.com/simi/mongoid_paranoia/pull/44

**Comment by dblock** [comment]
@Fudoshiki I'd like not to, unless we must because we just can't make it work.

**Comment by Fudoshiki** [comment]
ok

**Comment by Fudoshiki** [comment]
We can close this

**Comment by dblock** [comment]
Closing in favor of #219 .

**Pull request closed without merging**
