### PR TITLE
Added max_length, limit the size of the slug without its number part.

### PR DESCRIPTION
**Pull request by dblock**
This addresses #203, cc: @alloy.

### CODE REVIEW

**Comment by dblock** [comment]
There's also `Mongo::INDEX_KEY_LIMIT_BYTES`, maybe that should be the default? We do 

```ruby
  # slug composed of artist's slug and artwork title
  slug :artist_ids, :title, :cultural_maker, :published, index: true, history: true do |doc|
    if doc.published? || doc.has_slug?
      [
        doc.first_maker_text,
        doc.title
      ].map(&:presence).compact.join(' ')[0..Mongo::INDEX_KEY_LIMIT_BYTES - 30].to_url
    else
      doc.id.to_s
    end
  end
```

**Comment by alloy** [comment]
The code looks good to me :+1:

API-wise I have a question. Is the numerical part of the slug part of the index?
* If not, why are you subtracting 32 bytes from the default value?
* If it is, I wonder if it wouldn’t make more sense to make that an implementation detail; i.e. the max length you could assign would be 992. Having the user having to keep in mind and perform this calculation seems a tad confusing to me.

**Comment by dblock** [comment]
@alloy I'll edit the docs to make this clearer.

**Comment by alloy** [comment]
Thanks, that does make it more clear :+1: 

:shipit:

**Pull request merged**
