### PR TITLE
Mongoid HEAD support, PR #218 included [READY TO MERGE]

### PR DESCRIPTION
**Pull request by Fudoshiki**
https://github.com/digitalplaywright/mongoid-slug/pull/218
Still in progress, failing 2 tests

### CODE REVIEW

**Comment by Fudoshiki** [comment]
@dblock any ideas about?
~~~Failures:
  1) mongoid_slug:set when models parameter is passed goes though all documents of passed models and sets slug if not already set
     Failure/Error: const != const.upcase ? Mongoid::Slug > (Object.const_get const) : nil
     
     TypeError:
       compared with non class/module
     # ./lib/tasks/mongoid_slug.rake:6:in `>'
     # ./lib/tasks/mongoid_slug.rake:6:in `block (3 levels) in <top (required)>'
     # ./lib/tasks/mongoid_slug.rake:5:in `each'
     # ./lib/tasks/mongoid_slug.rake:5:in `find_all'
     # ./lib/tasks/mongoid_slug.rake:5:in `block (2 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:248:in `block in execute'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:243:in `each'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:243:in `execute'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:173:in `invoke'
     # ./spec/tasks/mongoid_slug_rake_spec.rb:41:in `block (3 levels) in <top (required)>'
  2) mongoid_slug:set when models parameter is not passed goes though all documents and sets slug if not already set
     Failure/Error: const != const.upcase ? Mongoid::Slug > (Object.const_get const) : nil
     
     TypeError:
       compared with non class/module
     # ./lib/tasks/mongoid_slug.rake:6:in `>'
     # ./lib/tasks/mongoid_slug.rake:6:in `block (3 levels) in <top (required)>'
     # ./lib/tasks/mongoid_slug.rake:5:in `each'
     # ./lib/tasks/mongoid_slug.rake:5:in `find_all'
     # ./lib/tasks/mongoid_slug.rake:5:in `block (2 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:248:in `block in execute'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:243:in `each'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:243:in `execute'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rake-11.2.0/lib/rake/task.rb:173:in `invoke'
     # ./spec/tasks/mongoid_slug_rake_spec.rb:68:in `block (3 levels) in <top (required)>'
~~~

**Comment by Fudoshiki** [comment]
@dblock Do we need mongoid 3 support? We can remove mongoid-compability if will drop mongoid 3

**Comment by dblock** [comment]
This looks great. Can I merge? Want to squash it?

**Comment by Fudoshiki** [comment]
@dblock Wait build pass and merge

**Comment by Fudoshiki** [comment]
@dblock Complete!

**Comment by dblock** [comment]
Excellent work @Fudoshiki

**Comment by dblock** [comment]
FYI was released in 5.3.0

**Pull request merged**
